"""First commit

Revision ID: 1f0edd7a3e41
Revises: 2095bf668848
Create Date: 2023-02-06 13:29:57.680750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0edd7a3e41'
down_revision = '2095bf668848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
