"""First commit

Revision ID: 2095bf668848
Revises: 9ad59b6531ec
Create Date: 2023-02-06 13:26:25.742214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2095bf668848'
down_revision = '9ad59b6531ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
