"""login delete

Revision ID: 776e005c8478
Revises: f009a83c8bf4
Create Date: 2023-02-06 13:09:57.328126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776e005c8478'
down_revision = 'f009a83c8bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
