"""First commit

Revision ID: 9ad59b6531ec
Revises: 72cee12192ca
Create Date: 2023-02-06 13:24:51.387318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad59b6531ec'
down_revision = '72cee12192ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
